mode: ContinuousDeployment

branches:
  develop:
    regex: ^develop$
    label: preview
    increment: Minor
  
  main:
    regex: ^main$
    label: rc
    increment: Patch
  
  hotfix:
    regex: ^hotfix[/-]
    label: rc
    increment: Patch
  
  release:
    regex: ^tags/v?\d+\.\d+\.\d+$
    label: ''
    source-branch:
      - main

ignore:
  sha: []