name: Build and Test

on: [workflow_call]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Get Version from Tag
        id: version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            TAG=${GITHUB_REF#refs/tags/v}
            echo "Using version $TAG"
            echo "version=$TAG" >> $GITHUB_OUTPUT
          else
            echo "Not a version tag...skipping package version."
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --configuration Release --settings tests.runsettings --verbosity normal

      - name: Pack Projects
        run: |
          if [[ -n "${{ steps.version.outputs.version }}" ]]; then
            dotnet pack --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -o ./artifacts
          else
            dotnet pack --no-build --configuration Release -o ./artifacts
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg