name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-preview:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-preview') || contains(github.ref, '-rc'))
    uses: ./.github/workflows/push-to-nuget.yml
    with:
      version: ${{ needs.build.outputs.version }}
    secrets: inherit

  publish-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
    uses: ./.github/workflows/publish-release.yml
    with:
      version: ${{ needs.build.outputs.version }}
    secrets: inherit
    