name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set.outputs.version }}
    steps:
      - name: Set Version from Context
        id: set
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "version=1.0.0-preview.${{ github.run_number }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: set-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.set-version.outputs.version }}

  publish:
    needs: build-and-test
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.set-version.outputs.version }}

  release:
    needs: [build-and-test, publish]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.set-version.outputs.version }}