name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build-and-test
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish.yml