name: Publish Preview

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish-preview:
    uses: ./.github/workflows/push-to-nuget.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit