name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Release Notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });

            const changelog = commits.flatMap(commit =>
              commit.commit.message
                .split('\n')[0]           // get the title/first line
                .split(';')               // split by semicolon
                .map(topic => `- ${topic.trim()}`) // clean and format
            ).join('\n');

            core.setOutput('notes', changelog);

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
