name: Compute Version

on:
  workflow_call:
    outputs:
      version:
        description: "Computed semver for this run"
        value: ${{ jobs.compute-version.outputs.version }}

jobs:
  compute-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.3.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          configFilePath: .github/GitVersion.yml

      - name: Set Version Output
        id: set-version
        run: echo "version=${{ steps.gitversion.outputs.FullSemVer }}" >> $GITHUB_OUTPUT
